# Generated by Django 3.0.5 on 2020-04-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_ajax', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=30)),
                ('price', models.IntegerField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
