# Generated by Django 3.0.5 on 2020-04-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_ajax', '0005_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='upload_pdf/cover_image/'),
        ),
        migrations.AlterField(
            model_name='books',
            name='pdf',
            field=models.FileField(upload_to='upload_pdf/pdf/'),
        ),
    ]
